# Generated by Django 3.2.4 on 2021-06-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('product', '0148_option_optionvalue_optionvaluechannellisting_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductOption', to='product.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='optionvaluechannellisting',
            unique_together={('option_value', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('option', 'product')},
        ),
    ]
