# Generated by Django 3.2.4 on 2021-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0148_option_productoption_productoptionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
