# Generated by Django 3.2.4 on 2021-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0115_order_order_type'),
        ('checkout', '0037_checkout_order_type'),
        ('product', '0149_auto_20210630_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='checkout_lines',
            field=models.ManyToManyField(related_name='option_values', to='checkout.CheckoutLine'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='order_lines',
            field=models.ManyToManyField(related_name='option_values', to='order.OrderLine'),
        ),
    ]
