# Generated by Django 3.2.4 on 2021-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0150_auto_20210716_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvaluechannellisting',
            name='price',
        ),
        migrations.AddField(
            model_name='optionvaluechannellisting',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='optionvaluechannellisting',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
