# Generated by Django 3.2.4 on 2021-07-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_auto_20210717_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionvaluechannellisting',
            options={'ordering': ('price_amount', 'pk')},
        ),
    ]
