# Generated by Django 3.2.4 on 2021-10-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_alter_optionvaluechannellisting_price_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='store',
        ),
    ]
