# Generated by Django 3.2.4 on 2021-10-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0156_auto_20211026_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'pk'), 'permissions': (('manage_products', 'Manage products.'),)},
        ),
    ]
