# Generated by Django 3.2.4 on 2021-10-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0158_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'pk'), 'permissions': (('manage_products', 'Manage products.'),)},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='category_p_meta_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='category_meta_idx',
        ),
    ]
