# Generated by Django 3.2.4 on 2022-01-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0161_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
