# Generated by Django 3.2.4 on 2022-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0162_product_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
