# Generated by Django 3.2.4 on 2022-01-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0163_category_enable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('name', 'pk', 'sort_order')},
        ),
        migrations.AddField(
            model_name='option',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
