# Generated by Django 3.2.4 on 2022-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0164_auto_20220119_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ('name', 'pk', 'sort_order')},
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
