# Generated by Django 3.2.4 on 2022-01-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0166_auto_20220120_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('sort_order', 'name', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ('sort_order', 'name', 'pk')},
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='private_metadata',
        ),
    ]
