# Generated by Django 3.2.4 on 2022-02-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0168_alter_option_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ('sort_order', 'pk')},
        ),
        migrations.AddField(
            model_name='productoption',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
