# Generated by Django 3.2.4 on 2022-02-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0169_auto_20220207_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('name', 'pk')},
        ),
    ]
