# Generated by Django 3.2.4 on 2022-02-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0170_alter_option_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
    ]
