# Generated by Django 3.2.4 on 2022-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0171_alter_option_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='enable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='max_options',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
