# Generated by Django 3.2.4 on 2021-06-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(max_length=256)),
                ('delivery_fee', models.FloatField()),
                ('free_delivery', models.FloatField()),
                ('min_order', models.FloatField()),
            ],
        ),
    ]
