# Generated by Django 3.2.4 on 2021-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='free_delivery',
            new_name='from_delivery',
        ),
    ]
