# Generated by Django 3.2.4 on 2021-06-29 08:19

from django.db import migrations
import saleor.core.db.fields
import saleor.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_free_delivery_delivery_from_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_area',
            field=saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js),
        ),
    ]
