# Generated by Django 3.2.4 on 2021-07-01 08:08

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('delivery', '0004_auto_20210630_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='store.store'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='delivery_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='delivery_meta_idx'),
        ),
    ]
