# Generated by Django 3.2.4 on 2021-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210701_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='from_delivery',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
