# Generated by Django 3.2.4 on 2021-06-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('shipping', '0030_auto_20210415_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_methods', to='store.store'),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_zones', to='store.store'),
        ),
    ]
