# Generated by Django 3.2.4 on 2021-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0030_auto_20210623_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_status',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_status',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webshop_status',
            field=models.DateField(blank=True, null=True),
        ),
    ]
