# Generated by Django 3.2.4 on 2021-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0031_auto_20210630_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pickup_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='webshop_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
