# Generated by Django 3.2.4 on 2021-07-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0032_auto_20210630_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
