# Generated by Django 3.2.4 on 2021-06-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('warehouse', '0014_remove_warehouse_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='store.store'),
        ),
    ]
