# Generated by Django 3.2.4 on 2021-11-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0125_auto_20211119_0455'),
        ('payment', '0029_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order'),
        ),
    ]
