# Generated by Django 3.2.4 on 2021-07-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicetime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetime',
            options={'ordering': ('store_id', 'pk'), 'permissions': (('manage_service_time', 'Service time.'),)},
        ),
    ]
