# Generated by Django 3.2.4 on 2021-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicetime', '0002_alter_servicetime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetime',
            name='dl_delivery_time',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='dl_time_gap',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='pu_delivery_time',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicetime',
            name='pu_time_gap',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
