# Generated by Django 3.2.4 on 2021-08-09 03:14

from django.db import migrations
import saleor.core.db.fields
import saleor.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('servicetime', '0003_auto_20210708_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetime',
            name='table_service_time',
            field=saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js),
        ),
    ]
