# Generated by Django 3.2.4 on 2021-07-29 02:55

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_auto_20210722_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('table_name', models.CharField(max_length=100)),
                ('table_qr_code', models.CharField(max_length=500)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_services', to='store.store')),
            ],
            options={
                'ordering': ('table_name', 'pk'),
                'permissions': (('manage_table_service', 'Table service.'),),
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
