# Generated by Django 3.2.4 on 2021-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0035_checkout_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=35),
        ),
    ]
