# Generated by Django 3.2.4 on 2021-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0037_checkout_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
    ]
