# Generated by Django 3.2.4 on 2021-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0038_remove_checkout_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='expected_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='expected_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
