# Generated by Django 3.2.4 on 2021-07-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0039_auto_20210719_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
