# Generated by Django 3.2.4 on 2021-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0040_alter_checkout_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
