# Generated by Django 3.2.4 on 2021-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0041_checkout_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='expected_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
