# Generated by Django 3.2.4 on 2021-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0042_alter_checkout_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('dinein', 'Dine-in')], default='pickup', max_length=35),
        ),
    ]
