# Generated by Django 3.2.4 on 2021-06-23 14:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_multitenant.mixins
import saleor.core.utils.json_serializer
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('name', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=256)),
                ('logo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='store-media')),
                ('cover_photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='store-media')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('name', 'pk'),
                'permissions': (('manage_stores', 'Manage store.'),),
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
