# Generated by Django 3.2.4 on 2021-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210709_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contant_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='store',
            name='stripe_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
