# Generated by Django 3.2.4 on 2021-08-05 07:36

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210722_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='favicon',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='store-media'),
        ),
    ]
