# Generated by Django 3.2.4 on 2021-08-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='table_service_status',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
