# Generated by Django 3.2.4 on 2021-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210809_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_transaction_fee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
