# Generated by Django 3.2.4 on 2021-09-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_enable_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='index_cash',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='index_stripe',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
