# Generated by Django 3.2.4 on 2022-01-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_store_pos_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default=models.CharField(max_length=256), null=True),
        ),
    ]
