# Generated by Django 3.2.4 on 2022-01-18 07:21

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_domain_enable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('domain_custom', models.CharField(max_length=256, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customdomain', to='store.store')),
            ],
            options={
                'ordering': ('domain_custom', 'pk'),
                'permissions': (('manage_stores', 'Manage store.'),),
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
