# Generated by Django 3.2.4 on 2022-02-28 03:56

from django.db import migrations
import saleor.core.db.fields
import saleor.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220118_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='favicon_pwa',
            field=saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js),
        ),
    ]
