# Generated by Django 3.2.4 on 2022-02-28 04:58

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_store_favicon_pwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='favicon_pwa',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='store-media'),
        ),
    ]
