# Generated by Django 3.2.4 on 2022-02-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_store_favicon_pwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='favicon_pwa',
        ),
    ]
