# Generated by Django 3.2.4 on 2022-03-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_faviconpwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sound_notifications',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
