# Generated by Django 3.2.4 on 2021-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0014_attribute_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250),
        ),
    ]
