# Generated by Django 3.2.4 on 2021-10-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0015_alter_attribute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True),
        ),
    ]
