# Generated by Django 3.2.4 on 2021-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0027_auto_20210623_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
