# Generated by Django 3.2.4 on 2021-07-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_auto_20210719_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
