# Generated by Django 3.2.4 on 2021-07-21 10:07

from django.db import migrations
import saleor.core.db.fields
import saleor.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0117_remove_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='option_items',
            field=saleor.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=saleor.core.utils.editorjs.clean_editor_js),
        ),
    ]
