# Generated by Django 3.2.4 on 2021-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0119_alter_orderline_option_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
