# Generated by Django 3.2.4 on 2021-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
